name: Kojajd
version: '${project.version}'
main: pixel.ajd.Main
description: Plugin intermediario de Reports do Knights of Jabu
api-version: 1.19
commands:
  duvida:
  responder:
  perguntas:
  ajudante:
  ajd:
  pontos:
  verpontos:
  ajdcheck:
  darponto:
  tirarponto: